export enum TipoOrigemAnexoArquivo {
  CONFIGURACAO_SISTEMA = 'CONFIGURACAO_SISTEMA',

  PROCESSO_IMPORTACAO_CLIENTES = 'PROCESSO_IMPORTACAO_CLIENTES',

  PROCESSO_ATUALIZACAO_TELEFONES_CLIENTES = 'PROCESSO_ATUALIZACAO_TELEFONES_CLIENTES',

  CLIENTES = 'CLIENTES',

  SAC = 'SAC',

  PROCESSO_IMPORTACAO_LEAD = 'PROCESSO_IMPORTACAO_LEAD',

  CONTESTACAO_LEAD = 'CONTESTACAO_LEAD',

  PEDIDOS = 'PEDIDOS',

  TRANSFERENCIA_CARTEIRA_CONSULTOR = 'TRANSFERENCIA_CARTEIRA_CONSULTOR',

  ITEM_CORRECAO = 'ITEM_CORRECAO',

  NOTIFICACAO_GERAL = 'NOTIFICACAO_GERAL',

  USUARIO_LOG_OPERACAO = 'USUARIO_LOG_OPERACAO',
}
